version: '3'

services:
  db_mitra:
    image: arm64v8/postgres:14-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mitra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
