spring:
  flyway:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mitra

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8081